services:
  open-pi-voice-ia:
    image: open-pi-voice-ia-img
    container_name: open-pi-voice-ia
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
