voice:
  ros__parameters:
    model_path: /voices/amy.onnx 
    sample_rate: 22050
    audio_device: "plughw:2,0"
    startup_text: "Voice active. Hello World!"
    poweroff_text: "daisy... daisy.... give me your answer do, daysy......day.."